### PR TITLE
Add Australian English.

### PR DESCRIPTION
**Pull request by samwilson**
Add the [Australian English](https://en.wikipedia.org/wiki/Australian_English) code and name.

### CODE REVIEW

**Comment by Krinkle** [comment]
@samwilson Thanks for the PR. I've pushed a commit that updates fallback and Names data to the latest from MediaWiki (using getLangData.php, and cp). 

* https://github.com/Krinkle/intuition/commit/9dfd1ffc4cc047ba9f64a73bd578284809d5f934
* https://github.com/Krinkle/intuition/commit/b86332a2aba68befc2ba40036fe96d785a51e8de

Unfortunately, it seems `en-au` is not part of the update. Presumably because this code is not yet accepted by MediaWiki and translatewiki.net? The Intuition project follows those with regards to language codes and names. Please submit it there first. Once accepted, feel free to submit a PR that updates the data.

**Comment by samwilson** [comment]
Ah, that makes sense. Will do! Thanks.

**Comment by samwilson** [comment]
https://gerrit.wikimedia.org/r/#/c/mediawiki/core/+/452879/

**Comment by Krinkle** [comment]
@samwilson Regarding the latest feedback on that patch - looks like it'll require a longer process for translatewiki.net and MediaWiki. That's all good for various reasons, and I'd be awesome if you can help push that along.

But.. I'd also welcome collaborating with you to make this work in Intuition sooner. See https://github.com/Krinkle/intuition/issues/88.

**Comment by samwilson** [comment]
I'm going to follow this up over there. No need for this PR anymore I think. :)

Thanks for your help!

**Pull request closed without merging**
