### PR TITLE
Remove reflinks

### PR DESCRIPTION
**Pull request by zhaofengli**
The i18n of reFill (formerly Reflinks) is now handled
on Transifex.

### CODE REVIEW

**Comment by ricordisamoa** [comment]
:cry:

**Comment by Krinkle** [comment]
Updated to also remove entry in `domainInfo.json` and other additional translations.

**Comment by nemobis** [comment]
Do you know that Transifex is proprietary? (Just checking.)

**Comment by zhaofengli** [comment]
Yes, I do. Intuition is still being used as the I18N framework and Transifex is used only for coordinating the translation. That being said, no proprietary library is being used by reFill. The reason why I moved away from Translatewiki is that it separates the message files from the source repo, which is unnatural and breaks the workflow.

**Comment by nemobis** [comment]
> it separates the message files from the source repo, which is unnatural and breaks the workflow

I think the subject here is Intuition, rather? I think you mean that you prefer to avoid copying the source l10n from your repo to the Intuition repo every time you update them, right? We should probably track this concern in a feature request.

**Comment by nemobis** [comment]
@zhaofengli, Krinkle fixed issue #45. Is Intuition again usable for you? How can we support reflinks on translatewiki.net?

**Comment by zhaofengli** [comment]
@nemobis Sorry for taking this long. Looking at the changes, I believe that Intuition and Translatewiki are again usable for the tool! :+1: I have changed (zhaofengli/refill@e604853778bafe80484ad717e29ad14c6a072562) the tool to use the upstream version of Intuition via Composer. But how should we move the existing translations on Transifex to Translatewiki? And is there a way to access translator information (stored in the `@metadata` key in the message files) from the code? `rawMsg()` doesn't seem to be working.

**Comment by Nikerabbit** [comment]
Regarding access to @metadata, it is currently not possible. We did not think of a use case for it. It probably could be made available.

**Pull request closed without merging**
