### PR TITLE
Remove "langlist" from library

### PR DESCRIPTION
**Pull request by Krinkle**
See commit messages.

### CODE REVIEW

**Comment by Krinkle** [comment]
I'm gonna move ahead on this without pre-merge review so as to unblock https://github.com/Krinkle/intuition/issues/97, which is mostly orthogonal to this, but I want to prioritise.

@samwilson I'd still very much value your feedback on this post-merge. We could for example re-introduce this functionality in a different way if considered useful.

**Comment by Krinkle** [comment]
@MusikAnimal That's `getLangName()` and `getLangNames()`, which are kept and with no intention to remove them.

What I removed is `getAvailableLangs` which was an (in my opinion, now strange) subset of `getLangNames()` with only the names for language codes for which at least 1 translation among the built-in message directories. (e.g. not related to your tool's messages)

**Comment by MusikAnimal** [comment]
Ah, I see. I think I use `getAvailableLangs` to know what to populate in the language dropdown. If there are no translations, then it makes total sense for it to not be in the list.

**Comment by Krinkle** [comment]
@MusikAnimal Yeah, but it gets tricky when a user sets their language centrally to a language, and then a specific tool may not be translated in it, but yet it's a valid language to choose, and might even have non-English fallbacks first.

When rendering the subset locally only, how do you express a current value that's not in the list?

Central being, from https://tools.wmflabs.org/intuition/, available via the cookie (or from a wiki, with userlang parameter).

Anyhow, there's still a valid use for it, so I'll keep it, no problem.

**Comment by MusikAnimal** [comment]
> When rendering the subset locally only, how do you express a current value that's not in the list?

Good question! It looks like I just don't show a label at all. Instead there's just the i18n icon https://eventmetrics.wmflabs.org/?uselang=unknown All my apps have the same dropdown, so this seems fine. All languages fallback to the source language (in this case English), right?

**Pull request merged**
